-- MySQL Script generated by MySQL Workbench
-- 07/21/16 22:43:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema basealquiler
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema basealquiler
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `basealquiler` DEFAULT CHARACTER SET utf8 ;
USE `basealquiler` ;

-- -----------------------------------------------------
-- Table `basealquiler`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basealquiler`.`region` (
  `idregion` INT NOT NULL AUTO_INCREMENT,
  `nombre_region` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idregion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basealquiler`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basealquiler`.`departamento` (
  `iddepartamento` INT NOT NULL AUTO_INCREMENT,
  `idregion` INT NOT NULL,
  `nombre_departamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddepartamento`),
  INDEX `fk_departamento_region_idx` (`idregion` ASC),
  CONSTRAINT `fk_departamento_region`
    FOREIGN KEY (`idregion`)
    REFERENCES `basealquiler`.`region` (`idregion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basealquiler`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basealquiler`.`provincia` (
  `idprovincia` INT NOT NULL AUTO_INCREMENT,
  `idregion` INT NOT NULL,
  `iddepartamento` INT NOT NULL,
  `nombre_provincia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idprovincia`),
  INDEX `fk_provincia_region_idx` (`idregion` ASC),
  INDEX `fk_provincia_departamento_idx` (`iddepartamento` ASC),
  CONSTRAINT `fk_provincia_region`
    FOREIGN KEY (`idregion`)
    REFERENCES `basealquiler`.`region` (`idregion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_provincia_departamento`
    FOREIGN KEY (`iddepartamento`)
    REFERENCES `basealquiler`.`departamento` (`iddepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basealquiler`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basealquiler`.`persona` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `idregion` INT NOT NULL,
  `iddepartamento` INT NOT NULL,
  `idprovincia` INT NOT NULL,
  `tipo_documento` VARCHAR(20) NOT NULL,
  `num_documento` VARCHAR(20) NOT NULL,
  `nombre_persona` VARCHAR(45) NOT NULL,
  `apaterno` VARCHAR(45) NOT NULL,
  `amaterno` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpersona`),
  INDEX `fk_persona_region_idx` (`idregion` ASC),
  INDEX `fk_persona_departamento_idx` (`iddepartamento` ASC),
  INDEX `fk_persona_provincia_idx` (`idprovincia` ASC),
  CONSTRAINT `fk_persona_region`
    FOREIGN KEY (`idregion`)
    REFERENCES `basealquiler`.`region` (`idregion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persona_departamento`
    FOREIGN KEY (`iddepartamento`)
    REFERENCES `basealquiler`.`departamento` (`iddepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persona_provincia`
    FOREIGN KEY (`idprovincia`)
    REFERENCES `basealquiler`.`provincia` (`idprovincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basealquiler`.`trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basealquiler`.`trabajador` (
  `idpersona` INT NOT NULL,
  `sueldo` DECIMAL(7,2) NOT NULL,
  `acceso` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idpersona`),
  CONSTRAINT `fk_trabajador_persona`
    FOREIGN KEY (`idpersona`)
    REFERENCES `basealquiler`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basealquiler`.`danza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basealquiler`.`danza` (
  `iddanza` INT NOT NULL AUTO_INCREMENT,
  `nombre_danza` VARCHAR(45) NOT NULL,
  `idregion` INT NOT NULL,
  `iddepartamento` INT NOT NULL,
  `idprovincia` INT NOT NULL,
  `descripcion` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`iddanza`),
  INDEX `fk_danza_region_idx` (`idregion` ASC),
  INDEX `fk_danza_departamento_idx` (`iddepartamento` ASC),
  INDEX `fk_danza_provincia_idx` (`idprovincia` ASC),
  CONSTRAINT `fk_danza_region`
    FOREIGN KEY (`idregion`)
    REFERENCES `basealquiler`.`region` (`idregion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_danza_departamento`
    FOREIGN KEY (`iddepartamento`)
    REFERENCES `basealquiler`.`departamento` (`iddepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_danza_provincia`
    FOREIGN KEY (`idprovincia`)
    REFERENCES `basealquiler`.`provincia` (`idprovincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basealquiler`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basealquiler`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(45) NOT NULL,
  `iddanza` INT NOT NULL,
  `talla` VARCHAR(45) NOT NULL,
  `caracteristicas` VARCHAR(45) NOT NULL,
  `precio_diario` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `stock` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idproducto`),
  INDEX `fk_producto_danza_idx` (`iddanza` ASC),
  CONSTRAINT `fk_producto_danza`
    FOREIGN KEY (`iddanza`)
    REFERENCES `basealquiler`.`danza` (`iddanza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basealquiler`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basealquiler`.`cliente` (
  `idpersona` INT NOT NULL,
  PRIMARY KEY (`idpersona`),
  CONSTRAINT `fk_cliente_persona`
    FOREIGN KEY (`idpersona`)
    REFERENCES `basealquiler`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basealquiler`.`boleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basealquiler`.`boleta` (
  `idcomprobante` INT NOT NULL,
  `idcliente` INT NOT NULL,
  `precio_total` DECIMAL(7,2) NOT NULL,
  `fecha` DATETIME NOT NULL,
  INDEX `fk_comprobante_pago_cliente1_idx` (`idcliente` ASC),
  PRIMARY KEY (`idcomprobante`),
  CONSTRAINT `fk_comprobante_pago_cliente`
    FOREIGN KEY (`idcliente`)
    REFERENCES `basealquiler`.`cliente` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basealquiler`.`detalleboleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basealquiler`.`detalleboleta` (
  `idcomprobante` INT NOT NULL,
  `idproducto` INT NOT NULL,
  `nombre_producto` VARCHAR(30) NOT NULL,
  `cantidad_producto` VARCHAR(10) NOT NULL,
  `precio_unitario` VARCHAR(10) NOT NULL,
  `subtotal` DECIMAL(7,2) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  INDEX `fk_detalleboleta_boleta_idx` (`idcomprobante` ASC),
  INDEX `fk_detalleboleta_producto_idx` (`idproducto` ASC),
  CONSTRAINT `fk_detalleboleta_boleta`
    FOREIGN KEY (`idcomprobante`)
    REFERENCES `basealquiler`.`boleta` (`idcomprobante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalleboleta_producto`
    FOREIGN KEY (`idproducto`)
    REFERENCES `basealquiler`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basealquiler`.`devolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basealquiler`.`devolucion` (
  `idcomprobante` INT NOT NULL,
  `idproducto` INT NOT NULL,
  `idtrabajador` INT NOT NULL,
  `fecha_recepcion` DATETIME NOT NULL,
  `cantidad` VARCHAR(45) NOT NULL,
  INDEX `fk_devolucion_detalleboleta_idx` (`idcomprobante` ASC),
  INDEX `fk_devolucion_trabajador_idx` (`idtrabajador` ASC),
  INDEX `fk_devolucion_producto_idx` (`idproducto` ASC),
  CONSTRAINT `fk_devolucion_detalleboleta`
    FOREIGN KEY (`idcomprobante`)
    REFERENCES `basealquiler`.`detalleboleta` (`idcomprobante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_devolucion_trabajador`
    FOREIGN KEY (`idtrabajador`)
    REFERENCES `basealquiler`.`trabajador` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_devolucion_producto`
    FOREIGN KEY (`idproducto`)
    REFERENCES `basealquiler`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basealquiler`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basealquiler`.`factura` (
  `idfactura` INT NOT NULL AUTO_INCREMENT,
  `idcliente` INT NOT NULL,
  `precio_total` DECIMAL(7,2) NOT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`idfactura`),
  INDEX `fk_factura_cliente_idx` (`idcliente` ASC),
  CONSTRAINT `fk_factura_cliente`
    FOREIGN KEY (`idcliente`)
    REFERENCES `basealquiler`.`cliente` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basealquiler`.`detallefactura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basealquiler`.`detallefactura` (
  `idfactura` INT NOT NULL,
  `idproducto` INT NOT NULL,
  `nombre_producto` VARCHAR(45) NOT NULL,
  `cantidad_producto` VARCHAR(10) NOT NULL,
  `precio_unitario` VARCHAR(45) NOT NULL,
  `subtotal` DECIMAL(7,2) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfactura`),
  INDEX `fk_detallefactura_producto_idx` (`idproducto` ASC),
  CONSTRAINT `fk_detallefactura_factura`
    FOREIGN KEY (`idfactura`)
    REFERENCES `basealquiler`.`factura` (`idfactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detallefactura_producto`
    FOREIGN KEY (`idproducto`)
    REFERENCES `basealquiler`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
